### PR TITLE
Unit Tests and Removing Facebook Functionality

### PR DESCRIPTION
**Pull request by CollierA13j**

### CODE REVIEW

**Review by wsciaroni — CHANGES_REQUESTED** [review]
## Overall
The code looks good!

### Failing Test
One test seems to be failing though, so we will need to take care of that before we can merge it in.

### Remaining Facebook References.

- I would like Facebook to be removed from the `pubspec.yaml` file [here](https://github.com/uah-cpe-sd-2020/myportion_app/blob/43291ccec6699fe7fc0c17149327f42993f1ae4c/pubspec.yaml#L17)
- `info.plst`
- `constants.dart`

And anywhere else Facebook is mentioned.  I'd really like to scrub the whole product of Facebook.

**Comment by wsciaroni** [comment]
I would like to add that in the future, it would likely be beneficial to have only one issue's fix per merge request.  What do you think? It might make the pull-requests more cohesive?

**Comment by CollierA13j** [comment]
So I can't remove Facebook from the AndroidManifest.xml because when I do, Flutter can no longer hook into the emulator for some reason. I'll remove the other mentions of Facebook. The regular expression used to validate the email might have to be changed to support the strange but valid email used to test

**Comment by wsciaroni** [comment]
@CollierA13j I removed the other references to Facebook on this branch if you'll do a pull.

I believe the issue you were running into was likely the `pubspec.yaml` still trying to use a Facebook dependency after removing it from the `AndroidManifest.MF`.

That should be fixed now.

**Comment by wsciaroni** [comment]
I also just noticed that you had mentioned #10 in this PR.  That issue appears to be about the user verifying their email address.  From my understanding this means that they should get an email that they have to confirm before the completion of their account creation.  Is this the story you worked on, or should it be #8 ?

**Comment by CollierA13j** [comment]
I did mean #8

**Comment by wsciaroni** [comment]
@CollierA13j 

Hope all is well.  Any update on this?

**Review by wsciaroni — APPROVED** [review]
Looks great!

Good work! Thank you

**Review by GuassianFlux — APPROVED** [review]

**Review by jalobrano — APPROVED** [review]

**Review by jlp0063 — APPROVED** [review]

**Comment by wsciaroni** [comment]
@CollierA13j Feel free to merge this in :)

**Pull request merged**
